version: '2'
services:
    bidirectmapstruct-app:
        image: bidirectmapstruct
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://bidirectmapstruct-postgresql:5432/bidirectmapstruct
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    bidirectmapstruct-postgresql:
        extends:
            file: postgresql.yml
            service: bidirectmapstruct-postgresql
